### PR TITLE
Version 3 - Rewrite and redesign

### PR DESCRIPTION
**Pull request by mnapoli**
Hey everyone, here comes externals v3!

This is a WIP with 2 goals:

- redesign the UI
- redesign the implementation to remove the older custom framework and go with pure serverless functions (with an attempt at a small bref framework)
- PHP 8 only

The preview is deployed here: https://v3.externals.io/

Feedback is very welcome!

### CODE REVIEW

**Comment by staabm** [comment]
great to see this project is still getting more love <3.

things which came into my mind while clicking thru the v3 app
- it loads google-analytics. are these numbers critical for you, or could the analysis be dropped?
- google analytics uses cookies and therefore I guess you would need a GDPR banner (or you drop GA)
- login with github does not work yet / I get a "invalid state" error
- I am using the "press 'n' for next unread message" feature a lot while reading thru the list. would be great it could be added back to v3

**Comment by mnapoli** [comment]
Thanks for the feedback, super useful!


>  it loads google-analytics. are these numbers critical for you, or could the analysis be dropped?

I'd like to keep some kind of analytics, and it bothers me a little bit to pay for a paid alternative for this website (that doesn't make any money). I'll think about it.

> google analytics uses cookies and therefore I guess you would need a GDPR banner (or you drop GA)

Good point, one more reason to switch to a paid service.

> login with github does not work yet / I get a "invalid state" error

Right, GitHub redirects you to `externals.io` instead of `v3.externals.io`, you can change the URL manually (keep the last part of the URL) and it should work.

> I am using the "press 'n' for next unread message" feature a lot while reading thru the list in v2. would be great it could be added back to v3

Once you manage to login you should be able to use this.

> if possible, it would be great if jQuery could be dropped

Yep I'm leaving that for another time for now, I've been working on this PR for too long now ^^

**Comment by mnapoli** [comment]
I have changed the infinite scrolling into a proper pagination.

**Comment by mnapoli** [comment]
image

**Pull request merged**
