### PR TITLE
Move to a serverless application with Bref

### PR DESCRIPTION
**Pull request by mnapoli**
I have changed the way externals.io is hosted: it is now a serverless application deployed with [Bref](https://bref.sh) on AWS Lambda.

That means we are no longer using Platform.sh, which is probably good news for those involved in externals.io's development since we had many troubles with that solution.

The new architecture is like this:

- website (PHP) running on AWS Lambda (and API Gateway)
- updater function (fetching new emails from the mailing list) running on AWS Lambda
- assets served via S3
- CloudFront as CDN to serve both assets and PHP over the same domain name
- I've left CloudFlare as well for now because it will reduce CloudFront costs, but I'll remove it if costs are negligible
- RDS for the MySQL database

Everything is configured in `serverless.yml`, and deployed via `make deploy`.

The main part of the cost should be related to the MySQL database, I'll see how it goes over the coming months. Hosting costs are covered by [null](https://null.tc/), my company.

Performances seem stable around 40ms for PHP's execution time:

Capture d’écran 2019-07-02 à 10 02 26

As far as I've tested everything works, let me know if there is any problem. Please note that the changes in this PR are currently live, I am opening this so that those interested can follow.

### CODE REVIEW

**Comment by staabm** [comment]
just did a few tests on externals.io live site and its looking really good so far

**Comment by staabm** [comment]
one thing I noticed: it seems there is a unresolved variable in the main.min.js

grafik

**Comment by mnapoli** [comment]
@staabm Thanks good point, I need to use a md5 hash I think.

**Comment by mnapoli** [comment]
That's solved!

**Pull request merged**
