### PR TITLE
added algolia svg and reduced search form size.

### LINKED ISSUE #16: Algolia Logo Low Res
image

Using a 5k imac, the image is pretty low res. Perhaps a 2x image is necessary?

### PR DESCRIPTION
**Pull request by staabm**
fixes #16

**before patch**

image

**~~after patch~~**

image

### CODE REVIEW

**Comment by alexbowers** [comment]
Thats pretty small, i'd say it should be bigger

**Comment by mnapoli** [comment]
Thanks, it looks very small though :/ I wonder if it's not ultra small on mobile (I remember it being very annoying when I added the logo). Also there seem to be a white background on the logo, maybe the one found here would be better: https://www.algolia.com/press#resources ?

**Comment by staabm** [comment]
I used the one provided in https://github.com/mnapoli/externals/issues/16#issuecomment-276690737

I am fine to use another one.. let me see.

**Comment by staabm** [comment]
Updated:

image

**Comment by staabm** [comment]
adjusted bootstrap cols for better mobile compat (new after patch screens):

image


image

**Comment by staabm** [comment]
Ping

**Comment by mnapoli** [comment]
Thanks

**Pull request merged**
